-- Mauricio Berón · backend definitivo
-- Ejecutar una vez en Supabase > SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  type text default 'Masterclass',
  short_description text,
  description text,
  program text,
  date date,
  time text,
  duration text,
  modality text,
  location text,
  price text,
  currency text default 'UYU',
  certificate boolean,
  purchase_url text,
  image_url text,
  status text default 'draft' check (status in ('draft','published','archived')),
  featured boolean default false,
  order_index integer default 1,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.courses alter column certificate drop default;
alter table public.courses enable row level security;

drop policy if exists "Public can read published courses" on public.courses;
create policy "Public can read published courses" on public.courses for select using (status='published' or (auth.jwt() ->> 'email')='mauricioberon@yahoo.com');
drop policy if exists "Mauricio can insert courses" on public.courses;
create policy "Mauricio can insert courses" on public.courses for insert to authenticated with check ((auth.jwt() ->> 'email')='mauricioberon@yahoo.com');
drop policy if exists "Mauricio can update courses" on public.courses;
create policy "Mauricio can update courses" on public.courses for update to authenticated using ((auth.jwt() ->> 'email')='mauricioberon@yahoo.com') with check ((auth.jwt() ->> 'email')='mauricioberon@yahoo.com');
drop policy if exists "Mauricio can delete courses" on public.courses;
create policy "Mauricio can delete courses" on public.courses for delete to authenticated using ((auth.jwt() ->> 'email')='mauricioberon@yahoo.com');

create table if not exists public.site_settings (
  id text primary key default 'main',
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);
alter table public.site_settings enable row level security;
drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings" on public.site_settings for select using (true);
drop policy if exists "Mauricio can insert site settings" on public.site_settings;
create policy "Mauricio can insert site settings" on public.site_settings for insert to authenticated with check ((auth.jwt() ->> 'email')='mauricioberon@yahoo.com');
drop policy if exists "Mauricio can update site settings" on public.site_settings;
create policy "Mauricio can update site settings" on public.site_settings for update to authenticated using ((auth.jwt() ->> 'email')='mauricioberon@yahoo.com') with check ((auth.jwt() ->> 'email')='mauricioberon@yahoo.com');
insert into public.site_settings(id,data) values ('main','{}'::jsonb) on conflict (id) do nothing;

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  page text not null,
  source text,
  medium text,
  campaign text,
  referrer text,
  created_at timestamptz default now()
);
alter table public.site_visits enable row level security;
drop policy if exists "Public can insert anonymous visits" on public.site_visits;
create policy "Public can insert anonymous visits" on public.site_visits for insert to anon with check (true);
drop policy if exists "Mauricio can read visits" on public.site_visits;
create policy "Mauricio can read visits" on public.site_visits for select to authenticated using ((auth.jwt() ->> 'email')='mauricioberon@yahoo.com');

insert into storage.buckets (id,name,public) values ('course-images','course-images',true) on conflict (id) do update set public=true;
insert into storage.buckets (id,name,public) values ('site-images','site-images',true) on conflict (id) do update set public=true;

drop policy if exists "Public course images" on storage.objects;
create policy "Public course images" on storage.objects for select using (bucket_id='course-images');
drop policy if exists "Mauricio uploads course images" on storage.objects;
create policy "Mauricio uploads course images" on storage.objects for insert to authenticated with check (bucket_id='course-images' and (auth.jwt() ->> 'email')='mauricioberon@yahoo.com');
drop policy if exists "Mauricio updates course images" on storage.objects;
create policy "Mauricio updates course images" on storage.objects for update to authenticated using (bucket_id='course-images' and (auth.jwt() ->> 'email')='mauricioberon@yahoo.com');
drop policy if exists "Mauricio deletes course images" on storage.objects;
create policy "Mauricio deletes course images" on storage.objects for delete to authenticated using (bucket_id='course-images' and (auth.jwt() ->> 'email')='mauricioberon@yahoo.com');
drop policy if exists "Public site images" on storage.objects;
create policy "Public site images" on storage.objects for select using (bucket_id='site-images');
drop policy if exists "Mauricio uploads site images" on storage.objects;
create policy "Mauricio uploads site images" on storage.objects for insert to authenticated with check (bucket_id='site-images' and (auth.jwt() ->> 'email')='mauricioberon@yahoo.com');
drop policy if exists "Mauricio updates site images" on storage.objects;
create policy "Mauricio updates site images" on storage.objects for update to authenticated using (bucket_id='site-images' and (auth.jwt() ->> 'email')='mauricioberon@yahoo.com');
drop policy if exists "Mauricio deletes site images" on storage.objects;
create policy "Mauricio deletes site images" on storage.objects for delete to authenticated using (bucket_id='site-images' and (auth.jwt() ->> 'email')='mauricioberon@yahoo.com');

insert into public.courses (
  slug,title,type,short_description,description,program,date,time,duration,modality,location,price,currency,certificate,purchase_url,status,featured,order_index
) values (
  'violencia-vicaria-ninas-ninos-adolescentes-pujas-parentales',
  'Violencia vicaria: niñas, niños y adolescentes en pujas parentales',
  'Masterclass',
  'Masterclass online sobre violencia vicaria y su impacto en niñas, niños y adolescentes en contextos de pujas parentales.',
  'Próxima masterclass del Lic. Mauricio Berón sobre violencia vicaria, con foco en niñas, niños y adolescentes involucrados en contextos de conflictividad y pujas parentales.',
  '',
  '2026-09-19','09:00 a 12:00','3 horas','Online','Online','3500','UYU',null,
  'https://wa.me/59899462504?text=Hola%20Lic.%20Mauricio%20Ber%C3%B3n%2C%20quisiera%20recibir%20informaci%C3%B3n%20e%20inscribirme%20a%20la%20masterclass%20Violencia%20vicaria%3A%20ni%C3%B1as%2C%20ni%C3%B1os%20y%20adolescentes%20en%20pujas%20parentales.',
  'published',true,1
)
on conflict (slug) do update set
  title=excluded.title,type=excluded.type,short_description=excluded.short_description,description=excluded.description,
  date=excluded.date,time=excluded.time,duration=excluded.duration,modality=excluded.modality,location=excluded.location,
  price=excluded.price,currency=excluded.currency,certificate=excluded.certificate,purchase_url=excluded.purchase_url,status='published',featured=true,updated_at=now();
